receivers:
  zipkin:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 10s
  memory_limiter:
    check_interval: 1s
    limit_mib: 300
  
exporters:
  debug:
    verbosity: detailed

  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  otlphttp/jaeger:
    endpoint: "http://jaeger:4318"
    tls:
      insecure: true
  
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

  otlphttp/prometheus:
    endpoint: "http://prometheus-service:9090/api/v1/otlp"
    tls:
      insecure: true
  
  loki:
    endpoint: "http://loki-service:3100/loki/api/v1/push"
    default_labels_enabled:
      exporter: false
      job: true

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [zipkin, otlp]
      processors: [batch, memory_limiter]
      exporters: [zipkin, otlp/jaeger]  # Export metrics to Prometheus 
    
    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [debug, otlphttp/prometheus]  # Export metrics to Prometheus

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, loki]  # Export logs to Loki