# Global config
global:
  scrape_interval: 15s   # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s   # Evaluate rules every 15 seconds. Default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration (currently commented out)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093  # Uncomment and set your Alertmanager address

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configuration
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    metrics_path: /metrics  # Corrected 'mertrics_path' to 'metrics_path'
    #schema: https
    static_configs:
      - targets: ["prometheus-service:9090"]
        labels:
          group: 'local'

  - job_name: "waveform-api"
    metrics_path: /metrics  # Corrected 'mertrics_path' to 'metrics_path'
    #schema: https
    static_configs:
      - targets: ["waveform-api-service:8080"]  # Ensure this endpoint is available over HTTPS
        labels:
          group: 'local-api'
        
